name: Get and insert sport news
on:
  schedule:
  - cron: "30 3,7,11,15,19,23 * * *"
  workflow_dispatch: 
jobs:
  get-insert-news:
    uses: ./.github/workflows/reusable-get-news.yml
    with:
      file-name: get-and-insert-sport.ts
    secrets: inherit