name: Get and insert tech news
on:
  schedule:
  - cron: "45 1,5,9,13,17,21 * * *"
  workflow_dispatch: 
jobs:
  get-insert-news:
    uses: ./.github/workflows/reusable-get-news.yml
    with:
      file-name: get-and-insert-tech.ts
    secrets: inherit