name: Get and insert business news
on:
  schedule:
    - cron: "00 0,4,8,12,16,20 * * *"
  workflow_dispatch: 
jobs:
  get-insert-news:
    uses: ./.github/workflows/reusable-get-news.yml
    with:
      file-name: get-and-insert-business.ts
    secrets: inherit