name: Get and insert latest news
on:
  schedule:
    - cron: "15 2,8,14,20 * * *"
  workflow_dispatch: 
jobs:
  get-insert-news:
    uses: ./.github/workflows/reusable-get-news.yml
    with:
      file-name: get-and-insert-news.ts
    secrets: inherit