name: Get News
on: [push, workflow_dispatch]
  #  schedule:
  #    - cron: "5 * * * *"
jobs:
  get-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm install

      - name: Run getNews
        run: npm run get-news